using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Hypercube.Ecs.Analyzers.Generators.AoT;

[Generator]
public sealed class ComponentMetaGenerator : IIncrementalGenerator
{
    public const string Name = "ComponentAoT";
    
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax or StructDeclarationSyntax,
                transform: static (ctx, _) => GetSemanticTarget(ctx))
            .Where(symbol => symbol is not null);

        var components = context.CompilationProvider.Combine(provider.Collect());

        context.RegisterSourceOutput(components, (spc, source) => Execute(source.Right!, spc));
    }

    private static ITypeSymbol? GetSemanticTarget(GeneratorSyntaxContext context)
    {
        if (context.SemanticModel.GetDeclaredSymbol(context.Node) is not ITypeSymbol symbol)
            return null;
        
        return symbol.AllInterfaces.Any(type => type.Name == Link.ComponentInterfaceName) ? symbol : null;
    }

    private static void Execute(ImmutableArray<ITypeSymbol> components, SourceProductionContext context)
    {
        if (components.IsDefaultOrEmpty)
            return;
        
        var sorted = components.OrderBy(c => c.ToDisplayString()).ToList();
        var sb = new StringBuilder();
        
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using Hypercube.Ecs.Components;");
        sb.AppendLine();
        sb.AppendLine("namespace Hypercube.Ecs.Generated;");
        sb.AppendLine();
        sb.Append("public static class ");
        sb.AppendLine(Name);
        sb.AppendLine("{");
        
        GenerateGetId(sb, sorted);
        
        sb.AppendLine("}");
        
        context.AddSource($"{Name}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void GenerateGetId(StringBuilder sb, List<ITypeSymbol> components)
    {       
        sb.AppendLine("    public static ComponentId GetId<T>() where T : struct, IComponent");
        sb.AppendLine("    {");
        sb.AppendLine("        return typeof(T) switch");
        sb.AppendLine("        {");
        
        for (var i = 0; i < components.Count; i++)
        {
            var component = components[i];
            
            sb.Append("            var t when t == typeof(");
            sb.Append(component.ToDisplayString());
            sb.Append(") => ");
            sb.Append(i);
            sb.AppendLine(",");
        }

        sb.AppendLine("            _ => throw new ArgumentException()");
        
        sb.AppendLine("        };");
        sb.AppendLine("    }");
    }
}