
using System.Collections.Frozen;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Hypercube.Ecs.Analyzers.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class EntityPackGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Hypercube.Ecs.Attributes.GenerateEntityPackAttribute";

    private static readonly FrozenSet<string> RequiredUsings = FrozenSet.Create(
        "System",
        "Hypercube.Ecs.Components",
        "JetBrains.Annotations"
    );

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var types = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is StructDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: static (context, _) => GetTargetType(context)
            )
            .Where(static t => t is not null);

        var compilationAndTypes = context.CompilationProvider.Combine(types.Collect());

        context.RegisterSourceOutput(compilationAndTypes, static (ctx, source) =>
        {
            var (compilation, structs) = source;
            foreach (var structSyntax in Enumerable.OfType<StructDeclarationSyntax>(structs))
            {
                GenerateOutput(ctx, compilation, structSyntax);
            }
        });
    }

    private static StructDeclarationSyntax? GetTargetType(GeneratorSyntaxContext context)
    {
        var type = (StructDeclarationSyntax) context.Node;
        foreach (var list in type.AttributeLists)
        {
            foreach (var attribute in list.Attributes)
            {
                var symbol = context.SemanticModel.GetSymbolInfo(attribute).Symbol as IMethodSymbol;
                var attributeType = symbol?.ContainingType;
                if (attributeType?.ToDisplayString() == AttributeFullName)
                    return type;
            }
        }

        return null;
    }

    private static void GenerateOutput(
        SourceProductionContext context,
        Compilation compilation,
        StructDeclarationSyntax typeSyntax)
    {
        var semanticModel = compilation.GetSemanticModel(typeSyntax.SyntaxTree);
        if (semanticModel.GetDeclaredSymbol(typeSyntax) is not INamedTypeSymbol symbol)
            return;

        var maxComponents = 0;
        foreach (var attr in symbol.GetAttributes())
        {
            if (attr.AttributeClass?.ToDisplayString() != AttributeFullName)
                continue;

            if (attr.ConstructorArguments.Length > 0 && attr.ConstructorArguments[0].Value is int value)
                maxComponents = value;
        }

        var namespaceName = symbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : symbol.ContainingNamespace.ToDisplayString();

        var typeName = symbol.Name;
        var source = GeneratePackedEntities(namespaceName, typeName, maxComponents);

        context.AddSource($"{typeName}.Pack.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private static string GeneratePackedEntities(string? namespaceName, string typeName, int maxComponents)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        foreach (var ns in RequiredUsings)
            sb.AppendLine($"using {ns};");

        sb.AppendLine();

        if (namespaceName != null)
        {
            sb.AppendLine($"namespace {namespaceName};");
            sb.AppendLine();
        }

        for (var count = 1; count <= maxComponents; count++)
        {
            var typeParams = string.Join(", ", Enumerable.Range(1, count).Select(i => $"T{i}"));

            var componentFields = string.Join("\n",
                Enumerable.Range(1, count)
                    .Select(i => $"    public readonly T{i} Component{i};"));

            var ctorParams = string.Join(", ",
                Enumerable.Range(1, count)
                    .Select(i => $"T{i} component{i}"));

            var assignments = string.Join("\n",
                Enumerable.Range(1, count)
                    .Select(i => $"        Component{i} = component{i};"));

            var implicitComponents = string.Join("\n\n",
                Enumerable.Range(1, count)
                    .Select(i =>
                        $"    public static implicit operator T{i}({typeName}<{typeParams}> arg) => arg.Component{i};"));

            var constraints = string.Join("\n",
                Enumerable.Range(1, count)
                    .Select(i => $"    where T{i} : IComponent"));

            sb.AppendLine("[PublicAPI]");
            sb.AppendLine($"public readonly struct {typeName}<{typeParams}>");
            sb.AppendLine(constraints);
            sb.AppendLine("{");

            sb.AppendLine("    public readonly Entity Id;");
            sb.AppendLine(componentFields);
            sb.AppendLine();

            sb.AppendLine($"    public {typeName}(Entity id, {ctorParams})");
            sb.AppendLine("    {");
            sb.AppendLine("        Id = id;");
            sb.AppendLine(assignments);
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine($"    public static implicit operator Entity({typeName}<{typeParams}> arg) => arg.Id;");
            sb.AppendLine(implicitComponents);

            sb.AppendLine("}");
            sb.AppendLine();
        }

        return sb.ToString();
    }
}